### ISSUE TITLE
[FR]For tags, move to "Search Tags".

### ISSUE THREAD

**Issue by kazdonkai** [iiz00/obsidian-multiple-notes-outline#11]
現在、タグが表示されている行では、それが含まれているファイルのオープンしかできませんが、Obsidian の挙動と同じように、リターンキーを押すか、コンテキストメニューで、タグの検索へそのタグをコピーして検索するようにして欲しいです。
よろしくご検討ください。

**Comment by iiz00** [comment]
なるほど、方法を調べてみます。しばらくお待ちいただければと思います。

**Comment by iiz00** [comment]
v0.3.0で、右クリックから検索できるようになっています。問題があればお知らせ下さい。
