### ISSUE TITLE
[FR] More Fine Setting of 2-hop Links for a Note in File View

### ISSUE THREAD

**Issue by fornewfork** [iiz00/obsidian-multiple-notes-outline#18]
There are four types of 2-hop links for Note A, which is as follows:

(1) Note A **->** Note B **<-** Note C

(2) Note A **->** Note  B **->** Note D

(3) Note A **<-** Note E **->** Note F

(4) Note A **<-** Note  E **<-** Note G

I interested in  (1)  and (3) since they can help me find some unnoticed connections.

Could we have a more fine setting such that only showing 2-hop links of type (1)  and type (3) are shown in your plugin, thanks!

**Comment by iiz00** [comment]
Thank you for your request!
I think it would not be possible to implement such a process, but I am honestly not sure if I would implement it or not, as it would complicate settings and internal processing.
I see that there are many examples that refer to the (1) you mention as a narrowly defined 2 hop links, so I can see that there is a need for such. On the other hand, it seems to me that links and backlinks can be turned on and off relatively easily from the icons.
I would like to ask about your use case, assuming you could hide (2) and (4) type links,
- Would you expect to use the normal elements, especially headings, links, and backlinks, in either visible or invisible state?
- Also, do you expect to switch (2) and (4) on and off frequently?

**Comment by fornewfork** [comment]
Thank you for the reply. Here is my concern which may not be correct.

- If possbile, I would permanently hide links of types (2) and (4).

- Actually, I would propose this feature request because the graph function can only switch on or off forward links or backward links in one direction.

And types (2) and (4) can actually be viewed through the graph.

For example, type (4)：Note A <- Note E <- Note G can be shown as follow

![image](https://github.com/iiz00/obsidian-multiple-notes-outline/assets/36132892/dd0a25aa-4d4a-4de0-9abc-008bf20ae501)


- Yet links of type (1) and (3) can help me navigate between notes.

- The issue with type (1) : Note A -> Note B <- Note C  has been mentioned by the proponent of Evergreen Notes, Andy. Here is the link https://notes.andymatuschak.org/zPpqLzE6VWKxXF6BpsAfr4C If you are interested.


- FYI, I had found two plugins can view links of type (1) .

- https://github.com/mottox2/obsidian-relation-pane?tab=readme-ov-file
![image](https://github.com/iiz00/obsidian-multiple-notes-outline/assets/36132892/b3ed4e00-6da0-496b-bcd5-5fa9aad61e0e)

- https://github.com/L7Cy/obsidian-2hop-links-plus
![image](https://github.com/iiz00/obsidian-multiple-notes-outline/assets/36132892/d28eed02-d78d-48dc-90da-96806605cf14)
I would also consider make a FR for that pulgin.

- I personally think that links of type (3) is a supplement to links of type (1).

**Comment by iiz00** [comment]
In v0.5.0, I added an option to limit the display of 2hop links as a trial (Settings → File View → Hide minor 2 hop links). I hope you will give it a try.

**Comment by iiz00** [comment]
I will close this issue for now. Please let me know if any problems arise.

**Comment by fornewfork** [comment]
Sorry for the late reply. I had check it and it works fine. Thank you!
