### ISSUE TITLE
FR: Outgoing links to work with embedded links

### ISSUE THREAD

**Issue by JenFau** [iiz00/obsidian-multiple-notes-outline#19]
Outgoing links work fine with ordinary links [[link]] but not embedded ones ![[link]]. 

Is it possible to included embedded ones, please?

**Comment by iiz00** [comment]
Thank you for your request!
It seems to be possible to treat the embedded links in the same way as regular links. To be honest, I did not realize this because I do not use embedding very often.
I would like to fix it, but I hope you can wait a while.

**Comment by iiz00** [comment]
In v0.5.0, embedded links are now treated as link elements. Please let me know if there are any problems.
