### ISSUE TITLE
supports clicking to jump to specific headings or lists In reading mode

### ISSUE THREAD

**Issue by calmwaves111** [iiz00/obsidian-multiple-notes-outline#21]
Thank you for your hard work. This plugin has really helped me a lot
Now I am encountering a problem where, in reading mode, clicking on an item does not redirect me to its row, while there is no problem at all in editing mode.
So can you support jumping in reading mode?

**Comment by iiz00** [comment]
Thanks for the report! Actually, I had not noticed it because I rarely use reading mode.... It is certainly not working. I will investigate the cause and fix it if I find out.

**Comment by iiz00** [comment]
Fixed in v0.5.1. Please let me know if there are any problems.

**Comment by calmwaves111** [comment]
Oh, everything is ok, thanks for all your hard work
