### ISSUE TITLE
Not Working for some reason

### ISSUE THREAD

**Issue by Bluemandan** [iiz00/obsidian-multiple-notes-outline#27]
Hey, I installed the plugin and realized it was not showing me anything. I made a completely fresh vault as well to see if there was any other plugins or settings messing with it, but it still did not work. It wasn't until I turned off headers and links off it would show it. Nor did it display any headers or text either way.

Any Ideas?
![1](https://github.com/iiz00/obsidian-multiple-notes-outline/assets/72044463/78418cea-57b9-4a00-afe9-f0343a2dddbb)
![2](https://github.com/iiz00/obsidian-multiple-notes-outline/assets/72044463/452ddaf1-a270-4ad0-b05a-38040b533b30)
![3](https://github.com/iiz00/obsidian-multiple-notes-outline/assets/72044463/dd4a1a14-47f3-47bc-becc-2290ace3460b)
![4](https://github.com/iiz00/obsidian-multiple-notes-outline/assets/72044463/d61e0a37-125c-4d2e-a07d-258707188c67)
![5](https://github.com/iiz00/obsidian-multiple-notes-outline/assets/72044463/686df0c3-2a39-4439-ae14-2dbfda2525df)
![6](https://github.com/iiz00/obsidian-multiple-notes-outline/assets/72044463/03c53c28-84f9-44ee-8fd7-e7370f6f9f26)
![7](https://github.com/iiz00/obsidian-multiple-notes-outline/assets/72044463/bdfd2df4-ee07-46d6-9cbd-d1535a46da88)
![8](https://github.com/iiz00/obsidian-multiple-notes-outline/assets/72044463/901764ce-7894-499c-b40e-f2b2593a9719)

**Comment by iiz00** [comment]
Thank you for using the plugin! 
I have attempted to fix the suspected cause in ~~v0.6.1~~v0.6.2. It appears to be a bug that was introduced in v0.6.0. Please test the new version and let me know if the issue persists. If it does, could you please open the Console with Ctrl+Shift+I and check if there are any error messages displayed? That would be very helpful for further troubleshooting.

**Comment by Bluemandan** [comment]
Everything is fixed! Thank you for the great plugin!

**Comment by Bluemandan** [comment]
Everything is fixed! Thank you for the great plugin!
