### ISSUE TITLE
[FR] Support for wikilinks in properties

### ISSUE THREAD

**Issue by kazdonkai** [iiz00/obsidian-multiple-notes-outline#7]
素晴らしいプラグインをありがとうございます。

Obsidianのインサイダービルドv.1.4.0 から、フロントマターのウィキリンクがリンクとして認識されるようになりました。
そこで、このプラグイン でも対応をお願いします。
形式 "[[wikilink]]"

画像では，"Author","Up" というproperty でいくつかのリンクがあります。
それが、Outgoing Link Files などで表示されてほしいわけです。
<img width="1239" alt="スクリーンショット 2023-09-07 22 44 11" src="https://github.com/iiz00/obsidian-multiple-notes-outline/assets/90127278/8d62aced-5c63-4c7a-af02-480779a56b35">

**Comment by kazdonkai** [comment]
お返事ありがとうございます。
ちょうど、2hops links plus プラグインの作者にもお願いして実装してもらったので、次が参考になるかも知れません。よろしくお願いします。

https://github.com/L7Cy/obsidian-2hop-links-plus/releases/tag/0.33.0 

ついでですが、ツィッターで紹介しておきました😉

https://x.com/kazdonmichi/status/1700153159107138045?s=61&t=U-xkjq8rrhTz6ZB7-5YVfw

**Comment by iiz00** [comment]
有用な情報と紹介、どうもありがとうございます！ 😄 
ちょっとだけ仕様を見てみたところ、アウトゴーイングリンクとして認識させるのは難しくなさそうですね。
バックリンクとして認識させるには、いくつか検討が必要そうです。dataviewプラグインが対応してくれると、そのキャッシュを利用して高速かつ簡単に取得できそうですが、リポジトリを見るとまだ対応していないようです（現状でも自前で多数のファイルのバックリンクファイルを取得すると結構遅いのですが、dataviewはバックリンクファイル情報を独自にキャッシュしているようで、かなり高速です）。また、ObsidianのロードマップにDatabasesとあり、これはおそらくdataview的な機能やキャッシュを実装すると思われるので、これによっても高速に取得できるようになる気がします。どちらの進捗もなければ低速ながら自前で実装するか…
調査を進めますので、しばらくお待ちいただければと思います。

**Comment by iiz00** [comment]
v0.2.0でプロパティ内のリンクに対応しました。不具合などあれば教えていただければ有り難いです😄 
Supported links in properties in v0.2.0. I would appreciate it if you could let us know if there are any problems.

**Comment by kazdonkai** [comment]
うまく表示されました。
対応ありがとうございます。
