### ISSUE TITLE
[BUG] Multiple notes outline doesn't follow light / dark mode

### ISSUE THREAD

**Issue by FeralFlora** [iiz00/obsidian-multiple-notes-outline#8]
When I switch between light and dark mode, Multiple Notes Outline stays in the previous mode until I close and reopen the pane.

![image](https://github.com/iiz00/obsidian-multiple-notes-outline/assets/33608083/8c862230-dc91-4ef9-af34-31871063e41b)

Multiple Notes Outline version: 0.1.4
Obsidian: 1.4.13
Theme: Prism

**Comment by iiz00** [comment]
Thank you for using the plugin 😄 
It is a specification at this time that the folder background color does not immediately change when switching between light and dark modes. Sorry about that.
However, it should be fixed by redrawing the view by clicking the leftmost icon in MNO view (update view), without restarting the MNO view. Does this not work?

Either way, I will look into a way to instantly reflect the light/dark mode.

**Comment by FeralFlora** [comment]
> Either way, I will look into a way to instantly reflect the light/dark mode.

Sorry to bother you, but it would be great if this got some attention, because as is, I close the Multiple notes outline sidebar every time I switch between light and dark mode. Especially going from light to dark mode, then Multiple notes outline is the only thing left that disturbs my vision. Otherwise, I would keep it open all the time.

**Comment by iiz00** [comment]
Sorry for your inconvenience. I will try to improve it.
But again, I think clicking the reload button will fix the colors, but does not work well?
In your screenshot, it is an icon like 🔃 on the bottom left of the MNO view.
Not a real time change, but easier than closing and reopening the view.

**Comment by FeralFlora** [comment]
> Sorry for your inconvenience. I will try to improve it. But again, I think clicking the reload button will fix the colors, but does not work well? In your screenshot, it is an icon like 🔃 on the bottom left of the MNO view. Not a real time change, but easier than closing and reopening the view.

Hey, no worries, and I'm sorry, I actually forgot about the refresh button—that makes a lot more manageable! However, it still is a bit jarring going to dark mode with the white file list at first. But don't lose any sleep over it, it will manage with the refresh button for now.

**Comment by iiz00** [comment]
In v0.2.0, MNO views should immediately reflect light/dark mode change.
I would appreciate it if you could let us know if there are any problems.

**Comment by FeralFlora** [comment]
> I would appreciate it if you could let us know if there are any problems.

No, this is working great for me now. Thanks a lot, I really appreciate it!
